# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentInterface',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('astm', 'ASTM E1381/E1394'), ('hl7', 'HL7 v2 (MLLP)'), ('poct1a', 'POCT1-A'), ('csv', 'Delimited file')], default='astm', max_length=16)),
                ('direction', models.CharField(choices=[('uni', 'Unidirectional (results only)'), ('bi', 'Bidirectional (orders and results)')], default='uni', max_length=8)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('test_code_map', models.JSONField(blank=True, default=dict, help_text='Instrument code → Dx test code')),
            ],
            options={
                'db_table': 'instrument_interfaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentMessage',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.TextField()),
                ('parsed_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Parsed', 'Parsed'), ('Applied', 'Applied to results'), ('Failed', 'Failed'), ('Ignored', 'Ignored')], default='Received', max_length=16)),
                ('accession_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('results_applied', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'instrument_messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LoincCode',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('loinc_code', models.CharField(max_length=32, unique=True)),
                ('long_name', models.TextField()),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.CharField(blank=True, max_length=64, null=True)),
                ('time_aspect', models.CharField(blank=True, max_length=64, null=True)),
                ('system', models.CharField(blank=True, max_length=128, null=True)),
                ('scale', models.CharField(blank=True, choices=[('Qn', 'Quantitative'), ('Ord', 'Ordinal'), ('Nom', 'Nominal'), ('Nar', 'Narrative')], max_length=8, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Active', max_length=32)),
            ],
            options={
                'db_table': 'loinc_codes',
                'ordering': ['loinc_code'],
            },
        ),
    ]
