# Generated by Django 5.2.17 on 2026-09-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interop', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentinterface',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='quality.equipment'),
        ),
        migrations.AddField(
            model_name='instrumentmessage',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='interop.instrumentinterface'),
        ),
        migrations.AddIndex(
            model_name='loinccode',
            index=models.Index(fields=['component'], name='loinc_codes_compone_90a5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumentmessage',
            index=models.Index(fields=['status', '-received_at'], name='instrument__status_18077f_idx'),
        ),
    ]
