# Generated by Django 5.2.17 on 2026-09-15 19:27

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0002_initial'),
        ('laboratory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10Code',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField()),
                ('chapter', models.CharField(blank=True, help_text="e.g. 'Endocrine, nutritional and metabolic diseases'", max_length=255)),
                ('category', models.CharField(blank=True, help_text='The three-character parent, e.g. E87 for E87.1', max_length=16)),
                ('billable', models.BooleanField(default=True, help_text='False for a category heading that is not itself codeable to a claim.')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'icd10_codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['category'], name='icd10_codes_categor_e05097_idx'), models.Index(fields=['billable'], name='icd10_codes_billabl_2d9e7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='HostQuery',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('specimen_identifier', models.CharField(db_index=True, help_text='What the analyser read from the tube — accession or container id.', max_length=64)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('not_found', 'No matching specimen'), ('no_work', 'Nothing outstanding'), ('refused', 'Refused')], default='answered', max_length=16)),
                ('tests', models.JSONField(blank=True, default=list, help_text='Test codes returned to the analyser.')),
                ('detail', models.TextField(blank=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='interop.instrumentinterface')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_queries', to='laboratory.order')),
            ],
            options={
                'db_table': 'host_queries',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['interface', '-requested_at'], name='host_querie_interfa_4ee8cc_idx'), models.Index(fields=['status', '-requested_at'], name='host_querie_status_d2737c_idx')],
            },
        ),
    ]
