# Generated by Django 5.2.17 on 2026-09-14 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompetency',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencies', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='usercompetency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recordlock',
            index=models.Index(fields=['expires_at'], name='record_lock_expires_38af41_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordlock',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='record_lock_unique_entity'),
        ),
        migrations.AddIndex(
            model_name='usercompetency',
            index=models.Index(fields=['user', 'status'], name='user_compet_user_id_b0bf7e_idx'),
        ),
    ]
