# Generated by Django 5.2.17 on 2026-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('installer', 'System Installer'), ('admin', 'Administrator'), ('manager', 'Laboratory Manager'), ('scientist', 'Biomedical Scientist'), ('medic', 'Medical Officer'), ('clerk', 'Clerk'), ('phlebotomist', 'Phlebotomist')], default='scientist', max_length=32),
        ),
    ]
