# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('GP', 'General practitioner'), ('Ward', 'Ward'), ('Clinic', 'Clinic'), ('Hospital', 'Hospital'), ('External', 'External laboratory')], max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('fax', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('delivery_preference', models.CharField(choices=[('portal', 'Portal'), ('email', 'Email'), ('print', 'Print'), ('fax', 'Fax'), ('hl7', 'HL7 interface')], default='portal', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requesters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DistributionRule',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('method', models.CharField(choices=[('portal', 'Portal'), ('email', 'Email'), ('print', 'Print'), ('fax', 'Fax'), ('hl7', 'HL7 interface')], max_length=16)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_release', models.BooleanField(default=False, help_text='Send as soon as the report is clinically verified')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='laboratory.testdefinition')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='reporting.requester')),
            ],
            options={
                'db_table': 'distribution_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionLog',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=16)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='laboratory.order')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='reporting.distributionrule')),
            ],
            options={
                'db_table': 'distribution_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.CharField(choices=[('SOP', 'Standard operating procedure'), ('Policy', 'Policy'), ('Manual', 'Manual'), ('Form', 'Form'), ('Safety', 'Safety data sheet'), ('Validation', 'Validation report')], max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In review'), ('Active', 'Active'), ('Superseded', 'Superseded'), ('Archived', 'Archived'), ('Obsolete', 'Obsolete')], default='Draft', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('review_due', models.DateField(blank=True, help_text='Scheduled periodic review', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('requires_acknowledgement', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.department')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='reporting.controlleddocument')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['category', 'title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_number__isnull', False)), fields=('document_number', 'version'), name='document_number_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='EmailQueueEntry',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('attachment_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='laboratory.order')),
            ],
            options={
                'db_table': 'email_queue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='email_queue_status_e1586b_idx')],
            },
        ),
    ]
