# Generated by Django 5.2.17 on 2026-09-15 19:27

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('key_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('secret_hash', models.CharField(editable=False, max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('organisation', models.CharField(blank=True, help_text='The receiving organisation, named on disclosure records.', max_length=255)),
                ('purpose', models.CharField(blank=True, help_text='Why this client exists — required for the minimum necessary standard.', max_length=255)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Optional allow-list of source addresses. Empty means any.')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this, the credential stops working.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('request_count', models.BigIntegerField(default=0, editable=False)),
                ('owner', models.ForeignKey(blank=True, help_text='Who is accountable for this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=128)),
                ('events', models.JSONField(blank=True, default=list)),
                ('include_identifiers', models.BooleanField(default=False, help_text='Send patient identifiers in the payload. Off by default: most subscribers only need to know something happened and can fetch the detail over the API, which is logged.')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, editable=False)),
                ('disabled_reason', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api.apiclient')),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=48)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('retrying', 'Retrying'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhook')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='webhook_del_status_20ffd3_idx'), models.Index(fields=['webhook', '-created_at'], name='webhook_del_webhook_b549ed_idx')],
            },
        ),
    ]
