# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhlebotomySchedule',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('ward_location', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('collection_type', models.CharField(choices=[('Routine', 'Routine'), ('STAT', 'STAT'), ('Timed', 'Timed')], default='Routine', max_length=32)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('InProgress', 'In progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'phlebotomy_schedules',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('test_key', models.CharField(help_text='Test id, or the reserved value REPORT for narrative rows', max_length=64)),
                ('value', models.TextField(blank=True, null=True)),
                ('numeric_value', models.FloatField(blank=True, help_text='Populated when the result parses as a number', null=True)),
                ('result_flags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Received', 'Received'), ('Resulted', 'Resulted'), ('Technically Validated', 'Technically Validated'), ('Clinically Verified', 'Clinically Verified'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Resulted', max_length=48)),
                ('entered_by', models.CharField(blank=True, max_length=150, null=True)),
                ('technical_validated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('clinical_verified_by', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'results',
                'ordering': ['test_key'],
            },
        ),
        migrations.CreateModel(
            name='ResultSignature',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('signed_by', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature_type', models.CharField(choices=[('technical', 'Technical'), ('clinical', 'Clinical')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result_signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('specimen_type', models.CharField(max_length=128)),
                ('retention_days', models.PositiveIntegerField()),
                ('temperature', models.CharField(blank=True, max_length=64, null=True)),
                ('disposal_method', models.CharField(default='Biohazard Disposal', max_length=128)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'retention_policies',
                'ordering': ['specimen_type'],
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128)),
                ('container_id', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'specimens',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenDisposal',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('disposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disposed_by', models.CharField(max_length=150)),
                ('batch_number', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specimen_disposals',
                'ordering': ['-disposed_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenReceiving',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.CharField(max_length=150)),
                ('condition', models.CharField(choices=[('Acceptable', 'Acceptable'), ('Marginal', 'Marginal'), ('Rejected', 'Rejected')], default='Acceptable', max_length=32)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=64, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Recollection-Required', 'Recollection required')], default='Accepted', max_length=32)),
            ],
            options={
                'db_table': 'specimen_receiving',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('units', models.CharField(blank=True, max_length=64, null=True)),
                ('tat_hours', models.FloatField(blank=True, null=True, verbose_name='turnaround target (hours)')),
                ('reference_range', models.JSONField(blank=True, help_text='Canonical shape: {min, max, panicLow, panicHigh}', null=True)),
                ('specimen_types', models.JSONField(blank=True, default=list)),
                ('methodology', models.CharField(blank=True, max_length=255, null=True)),
                ('loinc_code', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'test_definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationQueue',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='accounts.department')),
            ],
            options={
                'db_table': 'authorization_queues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Received', 'Received'), ('Resulted', 'Resulted'), ('Technically Validated', 'Technically Validated'), ('Clinically Verified', 'Clinically Verified'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=48)),
                ('order_by', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Order creation time')),
                ('priority', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('STAT', 'STAT')], default='Routine', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='patients.patient')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='laboratory.authorizationqueue')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-timestamp'],
            },
        ),
    ]
