# Generated by Django 5.2.17 on 2026-09-14 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
        ('quality', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reporting.requester'),
        ),
        migrations.AddField(
            model_name='phlebotomyschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phlebotomy_rounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phlebotomyschedule',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phlebotomy_rounds', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='phlebotomyschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phlebotomy_rounds', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='result',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='resultsignature',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='specimendisposal',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals', to='laboratory.retentionpolicy'),
        ),
        migrations.AddField(
            model_name='specimendisposal',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='laboratory.specimen'),
        ),
        migrations.AddField(
            model_name='specimenreceiving',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='specimenreceiving',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='quality.rejectioncriterion'),
        ),
        migrations.AddField(
            model_name='specimenreceiving',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='laboratory.specimen'),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='result',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='phlebotomyschedule',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='phlebotomy_rounds', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='order',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='orders', to='laboratory.testdefinition'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['order'], name='specimens_order_i_516a03_idx'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['container_id'], name='specimens_contain_912c43_idx'),
        ),
        migrations.AddIndex(
            model_name='testdefinition',
            index=models.Index(fields=['department', 'active'], name='test_defini_departm_ef4448_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['order'], name='results_order_i_0c1383_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['test', '-timestamp'], name='results_test_id_dc72c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('order', 'test_key'), name='results_order_test_unique'),
        ),
        migrations.AddIndex(
            model_name='phlebotomyschedule',
            index=models.Index(fields=['status', 'scheduled_at'], name='phlebotomy__status_094a98_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-timestamp'], name='orders_timesta_15235a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['patient', '-timestamp'], name='orders_patient_59b21c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['accession_number'], name='orders_accessi_56fe33_idx'),
        ),
    ]
