# Generated by Django 5.2.17 on 2026-09-15 19:27

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0003_icd10code_hostquery'),
        ('laboratory', '0002_initial'),
        ('patients', '0002_patient_merged_at_patient_merged_into'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDiagnosis',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code_value', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='1 is the primary indication.')),
                ('kind', models.CharField(choices=[('working', 'Working / provisional'), ('confirmed', 'Confirmed'), ('rule_out', 'Rule out'), ('history', 'Relevant history')], default='working', max_length=16)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'order_diagnoses',
                'ordering': ['rank', 'code_value'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='placer_order_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='source_message_id',
            field=models.CharField(blank=True, default='', help_text='Control id of the inbound message that created this order.', max_length=64),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='auto_verify_permitted',
            field=models.BooleanField(default=False, help_text='Allow decision rules to release results for this analyte without a person reading them. Off until the laboratory has validated autoverification for this test specifically — it is an analyte-scoped decision, not a system-wide mode.'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['placer_order_number'], name='orders_placer__ccabcb_idx'),
        ),
        migrations.AddField(
            model_name='orderdiagnosis',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_diagnoses', to='interop.icd10code'),
        ),
        migrations.AddField(
            model_name='orderdiagnosis',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='laboratory.order'),
        ),
        migrations.AddIndex(
            model_name='orderdiagnosis',
            index=models.Index(fields=['code_value'], name='order_diagn_code_va_5977e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderdiagnosis',
            constraint=models.UniqueConstraint(fields=('order', 'code_value'), name='order_diagnosis_unique'),
        ),
    ]
