# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedTest',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('test_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('formula', models.CharField(choices=[('ldl_friedewald', 'LDL (Friedewald)'), ('anion_gap', 'Anion gap'), ('a_g_ratio', 'Albumin/globulin ratio'), ('egfr_ckd_epi', 'eGFR (CKD-EPI 2021)'), ('corrected_calcium', 'Albumin-corrected calcium'), ('osmolality', 'Calculated osmolality'), ('transferrin_saturation', 'Transferrin saturation')], max_length=64)),
                ('inputs', models.JSONField(blank=True, default=list, help_text='Required input test codes')),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'calculated_tests',
                'ordering': ['test_code'],
            },
        ),
        migrations.CreateModel(
            name='CriticalValueAcknowledgment',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('acknowledged_by', models.CharField(max_length=150)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_clinician', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_method', models.CharField(blank=True, choices=[('phone', 'Telephone'), ('in-person', 'In person'), ('fax', 'Fax'), ('secure-message', 'Secure message')], max_length=32, null=True)),
                ('read_back_confirmed', models.BooleanField(default=False, help_text='The recipient repeated the result back — CAP GEN.41320')),
                ('notes', models.TextField(blank=True, null=True)),
                ('escalated_to', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'critical_value_acknowledgments',
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='CriticalValueNotification',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('test_code', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('threshold', models.CharField(max_length=64)),
                ('critical_type', models.CharField(choices=[('HIGH', 'Critically high'), ('LOW', 'Critically low')], max_length=8)),
                ('status', models.CharField(choices=[('Pending', 'Pending notification'), ('Acknowledged', 'Acknowledged'), ('Escalated', 'Escalated')], default='Pending', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('escalation_due_at', models.DateTimeField(blank=True, help_text='Unacknowledged notifications escalate after this time', null=True)),
            ],
            options={
                'db_table': 'critical_value_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeltaCheckFlag',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('previous_timestamp', models.DateTimeField(blank=True, null=True)),
                ('current_value', models.FloatField()),
                ('delta_percent', models.FloatField(blank=True, null=True)),
                ('delta_absolute', models.FloatField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.CharField(blank=True, max_length=150, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delta_check_flags',
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='DeltaCheckRule',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('test_code', models.CharField(max_length=64)),
                ('delta_type', models.CharField(choices=[('percent', 'Percent change'), ('absolute', 'Absolute change')], max_length=16)),
                ('threshold', models.FloatField()),
                ('direction', models.CharField(choices=[('any', 'Any direction'), ('increase', 'Increase only'), ('decrease', 'Decrease only')], default='any', max_length=16)),
                ('lookback_days', models.PositiveIntegerField(default=30, help_text='How far back to search for a comparable prior result')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'delta_check_rules',
                'ordering': ['test_code'],
            },
        ),
        migrations.CreateModel(
            name='DemographicReferenceRange',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('test_code', models.CharField(max_length=64)),
                ('age_min', models.IntegerField(blank=True, help_text='Inclusive lower bound in years', null=True)),
                ('age_max', models.IntegerField(blank=True, help_text='Inclusive upper bound in years', null=True)),
                ('gender', models.CharField(choices=[('All', 'All'), ('M', 'Male'), ('F', 'Female')], default='All', max_length=8)),
                ('pregnancy', models.BooleanField(default=False)),
                ('trimester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('low_normal', models.FloatField(blank=True, null=True)),
                ('high_normal', models.FloatField(blank=True, null=True)),
                ('low_critical', models.FloatField(blank=True, null=True)),
                ('high_critical', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'demographic_reference_ranges',
                'ordering': ['test_code', 'age_min'],
            },
        ),
        migrations.CreateModel(
            name='EpidemiologyNotification',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending review'), ('Reviewed', 'Reviewed'), ('Submitted', 'Submitted'), ('Closed', 'Closed')], default='Pending', max_length=32)),
                ('reviewed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=150, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Reference issued by the receiving authority', max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'epidemiology_notifications',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='NotifiableCondition',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_body', models.CharField(max_length=255)),
                ('timeframe', models.CharField(default='24h', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifiable_conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReflexActivation',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('trigger_value', models.CharField(max_length=64)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=32)),
            ],
            options={
                'db_table': 'reflex_activations',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ReflexRule',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('>', 'greater than'), ('>=', 'greater than or equal to'), ('<', 'less than'), ('<=', 'less than or equal to'), ('==', 'equal to')], max_length=4)),
                ('threshold', models.FloatField()),
                ('add_test_code', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'reflex_rules',
                'ordering': ['name'],
            },
        ),
    ]
