# Generated by Django 5.2.17 on 2026-09-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalvaluenotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_values', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='criticalvaluenotification',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_values', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='criticalvaluenotification',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_values', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='criticalvalueacknowledgment',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='clinical.criticalvaluenotification'),
        ),
        migrations.AddField(
            model_name='deltacheckflag',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_flags', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='deltacheckflag',
            name='previous_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delta_flags_as_previous', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='deltacheckflag',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_flags', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='deltacheckrule',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_rules', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='deltacheckflag',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='clinical.deltacheckrule'),
        ),
        migrations.AddField(
            model_name='demographicreferencerange',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_ranges', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='epidemiologynotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epidemiology_notifications', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='epidemiologynotification',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epidemiology_notifications', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='notifiablecondition',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='notifiable_conditions', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='epidemiologynotification',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinical.notifiablecondition'),
        ),
        migrations.AddField(
            model_name='reflexactivation',
            name='new_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflex_activations', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='reflexactivation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflex_activations', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='reflexrule',
            name='add_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflex_additions', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='reflexrule',
            name='trigger_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflex_triggers', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='reflexactivation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='clinical.reflexrule'),
        ),
        migrations.AddIndex(
            model_name='criticalvaluenotification',
            index=models.Index(fields=['status', '-created_at'], name='critical_va_status_aa1fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='deltacheckflag',
            index=models.Index(fields=['order'], name='delta_check_order_i_348397_idx'),
        ),
        migrations.AddIndex(
            model_name='deltacheckflag',
            index=models.Index(fields=['acknowledged_at'], name='delta_check_acknowl_3de5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='demographicreferencerange',
            index=models.Index(fields=['test', 'active'], name='demographic_test_id_83a7a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='epidemiologynotification',
            constraint=models.UniqueConstraint(fields=('order', 'condition'), name='epi_notification_unique'),
        ),
        migrations.AddConstraint(
            model_name='reflexactivation',
            constraint=models.UniqueConstraint(fields=('order', 'rule'), name='reflex_activation_unique'),
        ),
    ]
