# Generated by Django 5.2.17 on 2026-09-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiablecondition',
            name='timeframe_hours',
            field=models.PositiveIntegerField(default=24, help_text='The statutory window in hours. Kept alongside the label so overdue notifications can be found in SQL instead of by parsing the label on every row.'),
        ),
        migrations.AlterField(
            model_name='notifiablecondition',
            name='timeframe',
            field=models.CharField(default='24h', help_text='Label shown to users, e.g. 24h or 7d', max_length=32),
        ),
    ]
