# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControl',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('change_type', models.CharField(help_text='software | configuration | method | instrument', max_length=64)),
                ('impact_assessment', models.TextField(blank=True, null=True)),
                ('validation_evidence', models.TextField(blank=True, null=True)),
                ('rollback_plan', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Assessed', 'Impact assessed'), ('Approved', 'Approved'), ('Implemented', 'Implemented'), ('Verified', 'Verified in production'), ('Rejected', 'Rejected')], default='Requested', max_length=32)),
            ],
            options={
                'db_table': 'change_controls',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='CAPA-YYYY-NNNN', max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('qc_failure', 'QC failure'), ('pt_failure', 'Proficiency testing failure'), ('specimen', 'Specimen / pre-analytical'), ('instrument', 'Instrument'), ('result_error', 'Result error'), ('tat', 'Turnaround time'), ('complaint', 'Complaint'), ('safety', 'Safety'), ('privacy', 'Privacy / confidentiality'), ('other', 'Other')], max_length=32)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=16)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Action Planned', 'Action planned'), ('Implemented', 'Implemented'), ('Verifying', 'Verifying effectiveness'), ('Closed', 'Closed')], default='Open', max_length=32)),
                ('description', models.TextField(help_text='What happened')),
                ('immediate_action', models.TextField(blank=True, help_text='Containment / correction', null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True, help_text='To prevent recurrence', null=True)),
                ('preventive_action', models.TextField(blank=True, null=True)),
                ('effectiveness_check', models.TextField(blank=True, null=True)),
                ('patient_impact', models.BooleanField(default=False)),
                ('reported_results_affected', models.PositiveIntegerField(default=0)),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_entity_type', models.CharField(blank=True, max_length=64, null=True)),
                ('linked_entity_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'corrective_actions',
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='DisclosureAccounting',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('disclosed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disclosed_by', models.CharField(max_length=150)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_address', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('payment', 'Payment'), ('operations', 'Health care operations'), ('public_health', 'Public health reporting'), ('legal', 'Legal / court order'), ('patient_request', 'Patient request'), ('research', 'Research'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(help_text='What information was disclosed')),
                ('method', models.CharField(default='portal', max_length=32)),
                ('authorised_by_patient', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'disclosure_accounting',
                'ordering': ['-disclosed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgement',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('document_version', models.CharField(max_length=32)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'document_acknowledgements',
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('signer_printed_name', models.CharField(help_text='Captured at signing time — §11.50(a)(1)', max_length=255)),
                ('signer_role', models.CharField(max_length=32)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meaning', models.CharField(choices=[('authorship', 'Authored by'), ('review', 'Reviewed by'), ('technical_approval', 'Technically approved by'), ('clinical_approval', 'Clinically approved by'), ('release', 'Released by'), ('acknowledgement', 'Acknowledged by'), ('correction', 'Corrected by'), ('training', 'Training completed by')], max_length=32)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('record_hash', models.CharField(help_text='SHA-256 of the signed content — binds signature to record (§11.70)', max_length=64)),
                ('audit_sequence', models.BigIntegerField(blank=True, help_text='Position of the corresponding audit event', null=True)),
                ('reauthenticated', models.BooleanField(default=False, help_text='Signer re-entered their password at signing (§11.200(a)(1))')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'electronic_signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='MethodValidation',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('verification', 'Verification (FDA-cleared method)'), ('establishment', 'Establishment (LDT / modified method)'), ('revalidation', 'Revalidation')], default='verification', max_length=32)),
                ('performed_by', models.CharField(max_length=150)),
                ('started_on', models.DateField()),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('accuracy_verified', models.BooleanField(default=False)),
                ('precision_verified', models.BooleanField(default=False)),
                ('reportable_range_verified', models.BooleanField(default=False)),
                ('reference_interval_verified', models.BooleanField(default=False)),
                ('analytical_sensitivity', models.CharField(blank=True, max_length=128, null=True)),
                ('analytical_specificity', models.CharField(blank=True, max_length=128, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Superseded', 'Superseded')], default='In Progress', max_length=32)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'method_validations',
                'ordering': ['-started_on'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('treatment', 'Treatment'), ('research', 'Research use'), ('data_sharing', 'Data sharing'), ('marketing', 'Marketing'), ('genetic', 'Genetic testing')], max_length=32)),
                ('granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.CharField(max_length=150)),
                ('document_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_consents',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='PHIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('patient_mrn', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=8)),
                ('purpose', models.CharField(default='treatment', help_text='treatment | payment | operations | patient_request | legal', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('break_the_glass', models.BooleanField(default=False, help_text='Emergency override of normal access restrictions')),
                ('justification', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phi_access_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProficiencyResult',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('analyte', models.CharField(max_length=128)),
                ('sample_id', models.CharField(max_length=64)),
                ('reported_value', models.CharField(max_length=64)),
                ('target_value', models.CharField(blank=True, max_length=64, null=True)),
                ('acceptable_range', models.CharField(blank=True, max_length=128, null=True)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('Acceptable', 'Acceptable'), ('Unacceptable', 'Unacceptable'), ('Not Graded', 'Not graded')], default='Not Graded', max_length=32)),
            ],
            options={
                'db_table': 'proficiency_results',
                'ordering': ['analyte', 'sample_id'],
            },
        ),
        migrations.CreateModel(
            name='ProficiencySurvey',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text='e.g. CAP, RCPA, UK NEQAS', max_length=255)),
                ('survey_code', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('event', models.CharField(help_text='Shipment/event within the year', max_length=32)),
                ('discipline', models.CharField(max_length=128)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('attestation_signed', models.BooleanField(default=False, help_text='Attests no inter-laboratory communication occurred — CLIA §493.801(b)(4)')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proficiency_surveys',
                'ordering': ['-year', '-event'],
            },
        ),
        migrations.CreateModel(
            name='RetentionSchedule',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('record_class', models.CharField(choices=[('requisition', 'Test requisition'), ('test_record', 'Test record / result'), ('qc_record', 'Quality control record'), ('pt_record', 'Proficiency testing record'), ('instrument', 'Instrument maintenance record'), ('personnel', 'Personnel / competency record'), ('blood_bank', 'Immunohaematology record'), ('pathology', 'Pathology report'), ('cytology_slide', 'Cytology slide'), ('histology_block', 'Histology block'), ('audit', 'Audit trail')], max_length=32, unique=True)),
                ('retention_years', models.PositiveIntegerField()),
                ('citation', models.CharField(help_text='Regulatory basis for the period', max_length=255)),
                ('destruction_method', models.CharField(default='Secure electronic deletion', max_length=128)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retention_schedules',
                'ordering': ['record_class'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('process_area', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('likelihood', models.PositiveSmallIntegerField(help_text='1 (rare) – 5 (almost certain)')),
                ('severity', models.PositiveSmallIntegerField(help_text='1 (negligible) – 5 (catastrophic)')),
                ('existing_controls', models.TextField(blank=True, null=True)),
                ('mitigation', models.TextField(blank=True, null=True)),
                ('residual_likelihood', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_severity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Identified', 'Identified'), ('Mitigating', 'Mitigating'), ('Accepted', 'Accepted (residual)'), ('Closed', 'Closed')], default='Identified', max_length=32)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('next_review', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-likelihood', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('trainer', models.CharField(max_length=150)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Planned', max_length=32)),
                ('assessment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_records',
                'ordering': ['-completed_on'],
            },
        ),
        migrations.CreateModel(
            name='AccountSecurityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('must_change_password', models.BooleanField(default=False)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_security_state',
            },
        ),
        migrations.CreateModel(
            name='AmendedReport',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=2, help_text='Report version; 1 is the original')),
                ('reason', models.CharField(choices=[('transcription', 'Transcription error'), ('analytical', 'Analytical error'), ('specimen_mixup', 'Specimen identification error'), ('interpretation', 'Interpretation change'), ('addendum', 'Addendum / additional information'), ('other', 'Other')], max_length=32)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('corrected_value', models.TextField(blank=True, null=True)),
                ('narrative', models.TextField(help_text='Explanation printed on the amended report')),
                ('amended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinician_notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notified_by', models.CharField(blank=True, max_length=150, null=True)),
                ('notification_method', models.CharField(blank=True, max_length=32, null=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amended_reports',
                'ordering': ['-amended_at'],
            },
        ),
    ]
