# Generated by Django 5.2.17 on 2026-09-14 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
        ('quality', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amendedreport',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='amendedreport',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='laboratory.result'),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amendedreport',
            name='corrective_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='compliance.correctiveaction'),
        ),
        migrations.AddField(
            model_name='disclosureaccounting',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosures', to='laboratory.order'),
        ),
        migrations.AddField(
            model_name='disclosureaccounting',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='documentacknowledgement',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='reporting.controlleddocument'),
        ),
        migrations.AddField(
            model_name='documentacknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentacknowledgement',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_acknowledgements', to='compliance.electronicsignature'),
        ),
        migrations.AddField(
            model_name='amendedreport',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='compliance.electronicsignature'),
        ),
        migrations.AddField(
            model_name='methodvalidation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='methodvalidation',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='quality.equipment'),
        ),
        migrations.AddField(
            model_name='methodvalidation',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='phiaccesslog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_log', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='phiaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phi_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proficiencyresult',
            name='corrective_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_results', to='compliance.correctiveaction'),
        ),
        migrations.AddField(
            model_name='proficiencyresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_results', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='proficiencysurvey',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proficiencyresult',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.proficiencysurvey'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='reporting.controlleddocument'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['status', '-raised_at'], name='corrective__status_5f8f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='disclosureaccounting',
            index=models.Index(fields=['patient', '-disclosed_at'], name='disclosure__patient_5d49ab_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['entity_type', 'entity_id'], name='electronic__entity__b0ab06_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['signer', '-signed_at'], name='electronic__signer__2d50a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentacknowledgement',
            constraint=models.UniqueConstraint(fields=('document', 'document_version', 'user'), name='document_ack_unique'),
        ),
        migrations.AddConstraint(
            model_name='amendedreport',
            constraint=models.UniqueConstraint(fields=('order', 'version'), name='amended_report_version_unique'),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(fields=['patient', '-timestamp'], name='phi_access__patient_d70ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(fields=['username', '-timestamp'], name='phi_access__usernam_82ea18_idx'),
        ),
        migrations.AddConstraint(
            model_name='proficiencysurvey',
            constraint=models.UniqueConstraint(fields=('provider', 'survey_code', 'year', 'event'), name='pt_survey_unique'),
        ),
    ]
