# Generated by Django 5.2.17 on 2026-09-15 19:27

import apps.common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_retention_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='DSR-YYYY-NNNN', max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('access', 'Access (Art. 15)'), ('rectification', 'Rectification (Art. 16)'), ('erasure', 'Erasure (Art. 17)'), ('restriction', 'Restriction of processing (Art. 18)'), ('portability', 'Portability (Art. 20)'), ('objection', 'Objection (Art. 21)'), ('human_review', 'Human review of automated decision (Art. 22)')], max_length=24)),
                ('status', models.CharField(choices=[('received', 'Received'), ('identity_pending', 'Awaiting identity verification'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('partially_refused', 'Completed in part; partly refused'), ('refused', 'Refused'), ('withdrawn', 'Withdrawn by the subject')], default='received', max_length=24)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('extended', models.BooleanField(default=False)),
                ('extension_reason', models.TextField(blank=True)),
                ('requested_by', models.CharField(help_text='The subject, or a representative — recorded as given.', max_length=255)),
                ('relationship', models.CharField(blank=True, help_text='Self, parent, legal guardian, attorney, executor.', max_length=64)),
                ('detail', models.TextField(blank=True, help_text='What the subject actually asked for.')),
                ('identity_verified', models.BooleanField(default=False)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('identity_evidence', models.CharField(blank=True, help_text='What was checked, not a copy of it.', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('refusal_basis', models.TextField(blank=True, help_text='The specific legal basis for any refusal — Art. 12(4) requires it.')),
                ('export_path', models.CharField(blank=True, help_text='Where the encrypted export was written. Never the passphrase.', max_length=512)),
                ('records_erased', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'data_subject_requests',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRestriction',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_reason', models.TextField(blank=True)),
                ('permits_clinical_care', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'processing_restrictions',
                'ordering': ['-applied_at'],
            },
        ),
    ]
