# Generated by Django 5.2.17 on 2026-09-15 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_datasubjectrequest_processingrestriction'),
        ('patients', '0002_patient_merged_at_patient_merged_into'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsignature',
            name='automated_rule',
            field=models.ForeignKey(blank=True, help_text='Set when the signer is a rule, not a person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='meaning',
            field=models.CharField(choices=[('authorship', 'Authored by'), ('review', 'Reviewed by'), ('technical_approval', 'Technically approved by'), ('clinical_approval', 'Clinically approved by'), ('release', 'Released by'), ('acknowledgement', 'Acknowledged by'), ('correction', 'Corrected by'), ('training', 'Training completed by'), ('auto_verification', 'Autoverified by rule')], max_length=32),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasubjectrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_subject_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasubjectrequest',
            name='identity_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_subject_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasubjectrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='datasubjectrequest',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_requests', to='compliance.electronicsignature'),
        ),
        migrations.AddField(
            model_name='processingrestriction',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_restrictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingrestriction',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_restriction', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='processingrestriction',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions', to='compliance.datasubjectrequest'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['status', 'due_at'], name='data_subjec_status_847cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['patient', '-received_at'], name='data_subjec_patient_b0754b_idx'),
        ),
    ]
