# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(blank=True, max_length=64, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=64)),
                ('min_threshold', models.IntegerField(default=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('change', models.IntegerField(help_text='Positive for restock, negative for consumption')),
                ('reason', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance_after', models.IntegerField(blank=True, help_text='Stock level after the movement, for reconciliation', null=True)),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In progress'), ('Quarantine', 'In quarantine (awaiting QC)'), ('Released', 'Released'), ('Failed', 'Failed')], default='Scheduled', max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=150, null=True)),
                ('qc_passed', models.BooleanField(blank=True, help_text='Sterility/performance check before release', null=True)),
                ('released_by', models.CharField(blank=True, max_length=150, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_runs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('yield_amount', models.CharField(blank=True, db_column='yield', max_length=128, null=True)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ['name'],
            },
        ),
    ]
