# Generated by Django 5.2.17 on 2026-09-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='tests',
            field=models.ManyToManyField(blank=True, help_text='Tests that consume this reagent', related_name='reagents', to='laboratory.testdefinition'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='inventory.recipe'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['item', '-timestamp'], name='inventory_t_item_id_1e4337_idx'),
        ),
    ]
