# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiotic',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('drug_class', models.CharField(blank=True, db_column='class', max_length=128, null=True)),
                ('tier', models.PositiveSmallIntegerField(blank=True, help_text='Reporting tier for cascade/selective reporting', null=True)),
            ],
            options={
                'db_table': 'antibiotics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoBlock',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('block_id', models.CharField(help_text='Accession suffix, e.g. 2026-01-02-0001-A', max_length=64, unique=True)),
                ('tissue_type', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('Cassette Printed', 'Cassette printed'), ('Grossed', 'Grossed'), ('Processed', 'Processed'), ('Embedded', 'Embedded'), ('Sectioned', 'Sectioned'), ('Archived', 'Archived')], default='Cassette Printed', max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('grossed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('archive_location', models.CharField(blank=True, max_length=255, null=True)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histo_blocks', to='laboratory.specimen')),
            ],
            options={
                'db_table': 'histo_blocks',
                'ordering': ['block_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoSlide',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('slide_id', models.CharField(max_length=64, unique=True)),
                ('stain', models.CharField(help_text='H&E, PAS, IHC marker, …', max_length=64)),
                ('status', models.CharField(choices=[('Printed', 'Printed'), ('Stained', 'Stained'), ('Cover-slipped', 'Cover-slipped'), ('Released', 'Released to pathologist'), ('Archived', 'Archived')], default='Printed', max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stained_by', models.CharField(blank=True, max_length=150, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='specialty.histoblock')),
            ],
            options={
                'db_table': 'histo_slides',
                'ordering': ['slide_id'],
            },
        ),
        migrations.CreateModel(
            name='MicroCulture',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Setup', 'Set up'), ('Incubation', 'Incubating'), ('Reading', 'Being read'), ('Final', 'Final'), ('No Growth', 'No growth')], default='Setup', max_length=32)),
                ('incubator_location', models.CharField(blank=True, max_length=128, null=True)),
                ('setup_time', models.DateTimeField(blank=True, null=True)),
                ('preliminary_result', models.JSONField(blank=True, help_text='Gram stain and early morphology findings', null=True)),
                ('final_result', models.JSONField(blank=True, help_text='Organism identification and susceptibility profile', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='laboratory.order')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='laboratory.specimen')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultures', to='laboratory.testdefinition')),
            ],
            options={
                'db_table': 'micro_cultures',
                'ordering': ['-setup_time'],
            },
        ),
        migrations.CreateModel(
            name='SusceptibilityResult',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('organism', models.CharField(max_length=255)),
                ('mic', models.CharField(blank=True, help_text='Minimum inhibitory concentration', max_length=32, null=True)),
                ('zone_diameter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interpretation', models.CharField(choices=[('S', 'Susceptible'), ('I', 'Intermediate / susceptible-dose dependent'), ('R', 'Resistant'), ('NT', 'Not tested')], max_length=4)),
                ('reported', models.BooleanField(default=True, help_text='False when suppressed by cascade reporting')),
                ('standard', models.CharField(default='CLSI', help_text='CLSI or EUCAST breakpoints', max_length=32)),
                ('antibiotic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='susceptibilities', to='specialty.antibiotic')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susceptibilities', to='specialty.microculture')),
            ],
            options={
                'db_table': 'susceptibility_results',
                'ordering': ['organism', 'antibiotic__name'],
                'constraints': [models.UniqueConstraint(fields=('culture', 'organism', 'antibiotic'), name='susceptibility_unique')],
            },
        ),
    ]
