# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('compliance', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcMaterial',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=64)),
                ('expiration_date', models.DateField()),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, help_text='e.g. Level 1, Normal, High', max_length=32, null=True)),
            ],
            options={
                'db_table': 'qc_materials',
                'ordering': ['name', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='RejectionCriterion',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Quantity', 'Quantity'), ('Quality', 'Quality'), ('Labeling', 'Labelling'), ('Transport', 'Transport'), ('General', 'General')], default='General', max_length=32)),
            ],
            options={
                'db_table': 'rejection_criteria',
                'ordering': ['category', 'reason'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=128)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Under maintenance'), ('Retired', 'Retired')], default='Active', max_length=32)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='accounts.department')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Calibration', 'Calibration'), ('Error', 'Error'), ('Repair', 'Repair'), ('Verification', 'Function verification')], max_length=32)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='quality.equipment')),
            ],
            options={
                'db_table': 'equipment_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QcDefinition',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('test_code', models.CharField(max_length=64)),
                ('test_name', models.CharField(max_length=255)),
                ('mean', models.FloatField()),
                ('sd', models.FloatField()),
                ('unit', models.CharField(max_length=64)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_definitions', to='laboratory.testdefinition')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='quality.qcmaterial')),
            ],
            options={
                'db_table': 'qc_definitions',
                'ordering': ['test_code'],
            },
        ),
        migrations.CreateModel(
            name='QcRun',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('result_flags', models.JSONField(blank=True, default=list, help_text='Westgard rules violated, e.g. ["1-3s"]')),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Warning', 'Warning'), ('Fail', 'Fail')], default='Pass', max_length=16)),
                ('performed_by', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=True, help_text='False when the run is rejected and must be repeated')),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_runs', to='compliance.correctiveaction')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='quality.qcdefinition')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_runs', to='quality.equipment')),
            ],
            options={
                'db_table': 'qc_runs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='qcdefinition',
            constraint=models.UniqueConstraint(fields=('material', 'test_code'), name='qc_definition_unique'),
        ),
        migrations.AddIndex(
            model_name='qcrun',
            index=models.Index(fields=['definition', '-timestamp'], name='qc_runs_definit_b7427f_idx'),
        ),
        migrations.AddIndex(
            model_name='qcrun',
            index=models.Index(fields=['status'], name='qc_runs_status_b27ed1_idx'),
        ),
    ]
