# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('compliance', '0002_initial'),
        ('laboratory', '0002_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='mL', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=150)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('aliquot_specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derived_from', to='laboratory.specimen')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquots', to='laboratory.specimen')),
            ],
            options={
                'db_table': 'aliquots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature request'), ('General', 'General')], default='General', max_length=16)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Closed', 'Closed')], default='New', max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('freezer', 'Freezer'), ('fridge', 'Refrigerator'), ('rack', 'Rack'), ('box', 'Box'), ('shelf', 'Shelf'), ('room', 'Room')], max_length=16)),
                ('temperature', models.CharField(blank=True, max_length=32, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('rows', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('columns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='operations.storagelocation')),
            ],
            options={
                'db_table': 'storage_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TatThreshold',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('test', 'Test'), ('department', 'Department'), ('global', 'Global')], max_length=16)),
                ('target_hours', models.FloatField()),
                ('warning_hours', models.FloatField()),
                ('breach_hours', models.FloatField()),
                ('priority', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('STAT', 'STAT')], default='Routine', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tat_thresholds', to='accounts.department')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tat_thresholds', to='laboratory.testdefinition')),
            ],
            options={
                'db_table': 'tat_thresholds',
                'ordering': ['scope'],
            },
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Completed', 'Completed')], default='Draft', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheets', to='accounts.department')),
                ('orders', models.ManyToManyField(blank=True, related_name='worksheets', to='laboratory.order')),
                ('tests', models.ManyToManyField(blank=True, related_name='worksheets', to='laboratory.testdefinition')),
            ],
            options={
                'db_table': 'worksheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('printer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('supported_specimen_types', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=32)),
                ('max_throughput', models.PositiveIntegerField(default=100, help_text='Tests per hour, used for load balancing')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations', to='accounts.department')),
                ('instruments', models.ManyToManyField(blank=True, related_name='workstations', to='quality.equipment')),
                ('supported_tests', models.ManyToManyField(blank=True, related_name='workstations', to='laboratory.testdefinition')),
            ],
            options={
                'db_table': 'workstations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('specimen_type', models.CharField(blank=True, max_length=128, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='accounts.department')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='laboratory.testdefinition')),
                ('workstations', models.ManyToManyField(blank=True, help_text='Preferred workstations, highest priority first', related_name='routing_rules', to='operations.workstation')),
            ],
            options={
                'db_table': 'routing_rules',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ChainOfCustodyEvent',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('collected', 'Collected'), ('received', 'Received'), ('transferred', 'Transferred'), ('aliquoted', 'Aliquoted'), ('stored', 'Stored'), ('retrieved', 'Retrieved'), ('shipped', 'Shipped'), ('disposed', 'Disposed')], max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_custodian', models.CharField(blank=True, max_length=150, null=True)),
                ('to_custodian', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='compliance.electronicsignature')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='laboratory.specimen')),
            ],
            options={
                'db_table': 'coc_events',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['specimen', 'timestamp'], name='coc_events_specime_3cec6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_entity_type', models.CharField(blank=True, max_length=64, null=True)),
                ('related_entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Null for a broadcast', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('recipient_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='accounts.department')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'read', '-timestamp'], name='messages_recipie_ac92fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageAssignment',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, help_text='e.g. A3', max_length=32, null=True)),
                ('stored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stored_by', models.CharField(max_length=150)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_assignments', to='laboratory.specimen')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stored_specimens', to='operations.storagelocation')),
            ],
            options={
                'db_table': 'storage_assignments',
                'ordering': ['-stored_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('location', 'position'), name='storage_position_occupied_once')],
            },
        ),
        migrations.CreateModel(
            name='TatBreach',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('actual_hours', models.FloatField()),
                ('target_hours', models.FloatField()),
                ('breach_type', models.CharField(choices=[('warning', 'Approaching target'), ('critical', 'Target breached')], max_length=16)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tat_breaches', to='laboratory.order')),
            ],
            options={
                'db_table': 'tat_breaches',
                'ordering': ['-detected_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'breach_type'), name='tat_breach_unique_per_type')],
            },
        ),
        migrations.CreateModel(
            name='RoutingAssignment',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing', to='laboratory.order')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_assignments', to='laboratory.testdefinition')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.workstation')),
            ],
            options={
                'db_table': 'routing_assignments',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['workstation', 'status'], name='routing_ass_worksta_ba8b05_idx')],
            },
        ),
    ]
