# Generated by Django 5.2.17 on 2026-09-15 19:27

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_datasubjectrequest_processingrestriction'),
        ('laboratory', '0003_orderdiagnosis_order_placer_order_number_and_more'),
        ('operations', '0001_initial'),
        ('patients', '0002_patient_merged_at_patient_merged_into'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_label',
            field=models.CharField(blank=True, help_text='Who sent it when no user did — a decision rule, or the system.', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Null when the sender is not a person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExceptionItem',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('specimen_rejection', 'Specimen rejected'), ('critical_value', 'Critical value unacknowledged'), ('delta_check', 'Delta check flagged'), ('tat_breach', 'Turnaround time breached'), ('qc_failure', 'Quality control failure'), ('instrument', 'Instrument message failed'), ('interface_stale', 'Instrument interface silent'), ('inbound_message', 'Inbound message could not be processed'), ('webhook', 'Webhook delivery failing'), ('rule', 'Raised by a decision rule'), ('amended_report', 'Report amended after release'), ('proficiency', 'Proficiency testing deadline'), ('subject_request', 'Data subject request due'), ('manual', 'Raised by a person')], max_length=32)),
                ('source_key', models.CharField(help_text='Stable identity of the underlying problem, for deduplication.', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('test_code', models.CharField(blank=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_exceptions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exceptions', to=settings.AUTH_USER_MODEL)),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='compliance.correctiveaction')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='laboratory.order')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='patients.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exception_queue',
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['status', '-raised_at'], name='exception_q_status_582b68_idx'), models.Index(fields=['source', 'status'], name='exception_q_source_f05a11_idx'), models.Index(fields=['assigned_to', 'status'], name='exception_q_assigne_491e07_idx')],
            },
        ),
    ]
