# Generated by Django 5.2.17 on 2026-09-16 17:44

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_electronicsignature_automated_rule_and_more'),
        ('operations', '0002_message_sender_label_alter_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimePack',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=512)),
                ('encrypted', models.BooleanField(default=False)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('patient_count', models.PositiveIntegerField(default=0)),
                ('bytes_written', models.PositiveIntegerField(default=0)),
                ('generated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'downtime_packs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='DT-YYYY-NNNN', max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('planned', 'Planned (maintenance, upgrade, migration)'), ('unplanned', 'Unplanned (outage, failure, network loss)'), ('drill', 'Drill (testing the downtime procedure)')], default='unplanned', max_length=16)),
                ('began_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expected_end', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='What happened, in the words you would use to an inspector.')),
                ('impact', models.TextField(blank=True, help_text='Which disciplines and which workflows were affected.')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_notes', models.TextField(blank=True)),
                ('backloaded_results', models.PositiveIntegerField(default=0, editable=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('corrective_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_events', to='compliance.correctiveaction')),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_downtime', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_downtime', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_downtime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downtime_events',
                'ordering': ['-began_at'],
                'indexes': [models.Index(fields=['ended_at', '-began_at'], name='downtime_ev_ended_a_9cd14e_idx')],
            },
        ),
    ]
