# Generated by Django 5.2.17 on 2026-09-14 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sequence', models.BigIntegerField(help_text='Chain head at checkpoint time')),
                ('head_hash', models.CharField(max_length=64)),
                ('event_count', models.BigIntegerField()),
                ('verified', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'audit_chain_checkpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('acknowledged_by', models.CharField(blank=True, max_length=150, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_integrity_alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('sequence', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When the event reached the trail (vs. when it happened)')),
                ('actor_id', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('actor_username', models.CharField(db_index=True, default='system', editable=False, max_length=150)),
                ('actor_role', models.CharField(blank=True, editable=False, max_length=32, null=True)),
                ('entity_type', models.CharField(db_index=True, editable=False, max_length=64)),
                ('entity_id', models.CharField(db_index=True, editable=False, max_length=64)),
                ('entity_label', models.CharField(blank=True, default='', editable=False, help_text='Human-readable identity captured at event time', max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TECHNICAL_VALIDATE', 'Technical validation'), ('CLINICAL_VERIFY', 'Clinical verification'), ('RELEASE', 'Report release'), ('RESTORE', 'Restore from backup')], db_index=True, editable=False, max_length=48)),
                ('changes', models.JSONField(default=dict, editable=False, help_text="Field-level diff: {field: {'old': ..., 'new': ...}}")),
                ('reason', models.TextField(blank=True, editable=False, help_text='Justification supplied by the user, where the workflow requires one', null=True)),
                ('source', models.CharField(choices=[('web', 'Web interface'), ('api', 'API'), ('instrument', 'Instrument interface'), ('system', 'System / scheduled task'), ('migration', 'Data migration'), ('cli', 'Management command')], default='web', editable=False, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.TextField(blank=True, editable=False, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True)),
                ('session_key', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit trail',
                'db_table': 'audit_events',
                'ordering': ['-sequence'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-sequence'], name='audit_entity_idx'), models.Index(fields=['actor_username', '-timestamp'], name='audit_actor_idx'), models.Index(fields=['action', '-timestamp'], name='audit_action_idx'), models.Index(fields=['-timestamp'], name='audit_time_idx')],
            },
        ),
    ]
