# Generated by Django 5.2.17 on 2026-09-15 19:27

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('compliance', '0004_datasubjectrequest_processingrestriction'),
        ('laboratory', '0003_orderdiagnosis_order_placer_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this rule is for, in the words the laboratory would use.')),
                ('trigger', models.CharField(choices=[('result_entered', 'A result is entered or corrected'), ('result_validated', 'A result is technically validated'), ('order_created', 'An order is accessioned')], default='result_entered', max_length=32)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower numbers are evaluated first.')),
                ('stop_on_match', models.BooleanField(default=False, help_text='When this rule matches, skip every later rule for this result.')),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_version', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rules', to=settings.AUTH_USER_MODEL)),
                ('change_control', models.ForeignKey(blank=True, help_text='The change record authorising this rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='compliance.changecontrol')),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank to evaluate for every discipline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='accounts.department')),
                ('test', models.ForeignKey(blank=True, help_text='Leave blank to evaluate for every test.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='laboratory.testdefinition')),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('append_comment', 'Append an interpretive comment'), ('set_flag', 'Add a result flag'), ('add_test', 'Add a follow-on test to the order'), ('auto_verify', 'Request automatic verification'), ('hold', 'Hold the result from release'), ('raise_exception', 'Raise an item on the exception queue'), ('notify', 'Send an internal message')], max_length=24)),
                ('text', models.TextField(blank=True, help_text='Comment text, exception description or message body, as appropriate.')),
                ('flag', models.CharField(blank=True, help_text="For 'Add a result flag': the flag to add.", max_length=64)),
                ('recipient_role', models.CharField(blank=True, help_text="For 'Send an internal message': which role.", max_length=32)),
                ('severity', models.CharField(blank=True, default='medium', help_text="For 'Raise an item on the exception queue'.", max_length=16)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('add_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_rules', to='laboratory.testdefinition')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rules.rule')),
            ],
            options={
                'db_table': 'rule_actions',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('group', models.PositiveSmallIntegerField(default=0, help_text='Conditions in the same group must all hold; any group may match.')),
                ('subject', models.CharField(choices=[('result.value', 'Result — numeric value'), ('result.text', 'Result — text value'), ('result.flag', 'Result — flag (Normal/Low/High/Critical …)'), ('result.position', 'Result — position vs reference interval'), ('result.is_critical', 'Result — is a critical value'), ('result.has_delta', 'Result — triggered a delta check'), ('test.code', 'Test — code'), ('test.department', 'Test — department'), ('patient.age_years', 'Patient — age in years'), ('patient.age_days', 'Patient — age in days'), ('patient.sex', 'Patient — sex'), ('order.priority', 'Order — priority'), ('order.icd10', 'Order — ICD-10 diagnosis codes'), ('specimen.type', 'Specimen — type'), ('specimen.condition', 'Specimen — condition at reception'), ('prior.value', 'Previous result — numeric value'), ('prior.age_days', 'Previous result — days ago'), ('delta.percent', 'Change from previous — percent'), ('delta.absolute', 'Change from previous — absolute'), ('qc.status', 'Quality control — status for this test'), ('entry.source', 'Entry — source (manual or instrument)')], max_length=32)),
                ('operator', models.CharField(choices=[('eq', 'is'), ('ne', 'is not'), ('lt', 'is less than'), ('lte', 'is at most'), ('gt', 'is greater than'), ('gte', 'is at least'), ('between', 'is between'), ('in', 'is one of'), ('not_in', 'is not one of'), ('contains', 'contains'), ('blank', 'is blank'), ('not_blank', 'is not blank')], default='eq', max_length=16)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('value_to', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.rule')),
            ],
            options={
                'db_table': 'rule_conditions',
                'ordering': ['group', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.CharField(default=apps.common.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('test_code', models.CharField(blank=True, max_length=64)),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('actions_applied', models.JSONField(blank=True, default=list)),
                ('refusals', models.JSONField(blank=True, default=list, help_text='Guardrails that refused an action, with the reason.')),
                ('outcome', models.CharField(choices=[('applied', 'Actions applied'), ('partial', 'Some actions refused'), ('blocked', 'All actions refused'), ('overridden', 'Overridden by a user')], default='applied', max_length=16)),
                ('auto_verified', models.BooleanField(default=False)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_executions', to='laboratory.order')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_overrides', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_executions', to='laboratory.result')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='rules.rule')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_executions', to='compliance.electronicsignature')),
            ],
            options={
                'db_table': 'rule_executions',
                'ordering': ['-fired_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['trigger', 'active', 'priority'], name='rules_trigger_2a1835_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['test', 'active'], name='rules_test_id_e85871_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['order', '-fired_at'], name='rule_execut_order_i_6a0430_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['-fired_at'], name='rule_execut_fired_a_fbf9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['auto_verified', '-fired_at'], name='rule_execut_auto_ve_042ef4_idx'),
        ),
    ]
